stages:
  data_ingestion:
    cmd: python src/sing_language_conversion/pipeline/stage_01_data_ingestion.py
    deps:
      - src/sign_language_conversion/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image