AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 28
WEIGHTS: imagenet

n_estimators: 100
criterion: 'gini'
max_depth: None
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0.0
max_features: 'sqrt'
max_leaf_nodes: None
min_impurity_decrease: 0.0
bootstrap: True
oob_score: False
n_jobs: None
random_state: None
verbose: 0
warm_start: False
class_weight: None
ccp_alpha: 0.0
max_samples: None
monotonic_cst: None