artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vbz33uarAaRqm6iGHVIxBUhBxhkdfdUe/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_dataset: 
  root_dir: artifacts/prepare_dataset/root_dir
  dataset_path: artifacts/prepare_dataset

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pkl