artifacts_root: artifacts

data_creation:
  root_dir: artifacts/data_creation
  raw_dataset: artifacts/data_creation

data_pickle: 
  root_dir: artifacts/data_pickle
  pickle_dataset : artifacts/data_pickle/data.pkl

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training

  